### ISSUE TITLE
Deploy the project and link to the demo in the README

### ISSUE THREAD

**Issue by veselinn** [Lyserg-Diethel/react-weather-app#1]
Hey, Stefan :wave: 

It would be awesome if you could deploy this somewhere (Digital Ocean/Vercel/somewhere with a free tier/etc.) and add a link in the README.md.
This will allow people to check it out without downloading and running the code.
What do you think about this?

All the best :vulcan_salute:

**Comment by Lyserg-Diethel** [comment]
Hey @veselinn,

That sounds really good. Thanks for the idea! 💎

You can find a link to Vercel in the README now.

Have a great day! ✨
